name: Generate Release

on:
  push:
    branches:
      - master

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Tag with Gradle
      run: ./gradlew tagGithub
